#!/usr/bin/expect -f
set timeout 10

spawn npm adduser --registry http://0.0.0.0:4873/
match_max 100000

expect "Username"
send "theia-build\r"

expect "Password"
send "The14-8uiLd\r"

expect "Email: (this IS public)"
send "theia@eclipse.org\r"

expect "Logged in on http://0.0.0.0:4873/."