name: 3PP License Check

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 4 * * *' # Runs every day at 4am: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

jobs:

  License-check:
    name: 3PP License Check using dash-licenses

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18]
        java: [11]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Use Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Run dash-licenses
        shell: bash
        run: |
          yarn --frozen-lockfile --ignore-scripts
          yarn license:check
        env:
          DASH_TOKEN: ${{ secrets.DASH_LICENSES_PAT }}